"""init

Revision ID: 27cfbc3fbce1
Revises: dd765d2371c7
Create Date: 2026-05-14 01:11:48.373953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '27cfbc3fbce1'
down_revision: Union[str, Sequence[str], None] = 'dd765d2371c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zametki', sa.Column('structured_text', sa.Text(), nullable=True))
    op.add_column('zametki', sa.Column('has_conflict', sa.Boolean(), nullable=False))
    op.add_column('zametki', sa.Column('conflict_with_id', sa.BigInteger(), nullable=True))
    op.add_column('zametki', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.add_column('zametki', sa.Column('is_reminded', sa.Boolean(), nullable=False))
    op.add_column('zametki', sa.Column('remind_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('zametki', sa.Column('tg_chat_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zametki', 'tg_chat_id')
    op.drop_column('zametki', 'remind_at')
    op.drop_column('zametki', 'is_reminded')
    op.drop_column('zametki', 'embedding')
    op.drop_column('zametki', 'conflict_with_id')
    op.drop_column('zametki', 'has_conflict')
    op.drop_column('zametki', 'structured_text')
    # ### end Alembic commands ###
