"""add_recurrence_fields

Revision ID: a6b380f786c6
Revises: 27cfbc3fbce1
Create Date: 2026-05-14 01:42:52.691331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6b380f786c6'
down_revision: Union[str, Sequence[str], None] = '27cfbc3fbce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zametki', sa.Column('recurrence', sa.String(length=50), nullable=True))
    op.add_column('zametki', sa.Column('repetitions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zametki', 'repetitions')
    op.drop_column('zametki', 'recurrence')
    # ### end Alembic commands ###
