"""add tag

Revision ID: dd765d2371c7
Revises: a085f48d2d60
Create Date: 2026-01-21 20:12:08.397155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd765d2371c7'
down_revision: Union[str, Sequence[str], None] = 'a085f48d2d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zametki', sa.Column('tag', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zametki', 'tag')
    # ### end Alembic commands ###
